language: node_js
node_js:
    - "8"

cache:
    yarn: true
    directories: 
        - node_modules
        - build

before_deploy:
    - "yarn build"
    - "ls -a"

deploy:
  provider: firebase
  token:
    secure: "GgrRQVtWS9OXWAfZon10Nm6IgO1Q58nTqFM/itbTswfYxljfmoTaVzLbedkbINGsP0/hugdKZZAIJA9px6bUC26YB0rg4ToSiT+5ZBb2ROSy24U4XkpYJyHVhNW1kZJsGLkS5YgdOJyYD37kMM4+x0uCWgHXrY8Z+IUdk1fCOuFQdkk38ExeVgAjaekJtHcPZ87erj3XM4QLhmf248L2tjPLurn4RS2d51ID5sTeG2mxErsP6sP6D9QHY/OVP5CLwjsyKe/TWleI0oUkssgR0aRpYSNhbE7qYI5FpSA7cOZ1YDBsTS2ngrcw4SzDAZCXDRAIKqirBIe3qkmRVgYgdFfJysAiFRC8a5ld81Hj1x8vU0ooO9av2n1+oXLB17Ko1gJG/V6TcvD4dEhdMYR2CDMQu1EQCtx8tLu2SA5xDUxHy7mSVzrANTHo5H594xHw2ALYoQTkmP/HkP8lVWAHon8VAdmaXwK5SebD4ixaQKkoLM0lGQRuieoDWhxkewrJtRmLRDmGcSBRZVBttbPwcXacbYJtCIO6u0SDn0VlIM0vxY+OSXW/6D9fiW3eie22NWC9ie8yFrkul0Mv5hgRcyRUn5iOBDvC4/7D7/G8l2UvEvq1OpdEnUTpk9xZppPfkpRCLafPdq5pFljRCFZY2ZG9z0QpclgjXWN4BDFqfbE="
  skip_cleanup: true
  message: "deploying to Firebase"

